dist: xenial
language: node_js
sudo: false
services:
  - xvfb
node_js:
  - lts/*
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
  #- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
